### ISSUE TITLE
Overflow Issue

### ISSUE THREAD

**Issue by yukthr** [costastf/micropython_hourly_sleeper_library#1]
Hi Costas,

Thank you for the library. When i try this on ESP8266 i see the below error 

`Entering DeepSleep
Sleeping for hour 1 of 8
Traceback (most recent call last):
  File "main.py", line 71, in <module>
  File "main.py", line 69, in whole_loop
  File "main.py", line 57, in sleep_hours
  File "hourlysleeper.py", line 67, in __call__
  File "hourlysleeper.py", line 64, in _check
  File "hourlysleeper.py", line 53, in _sleep
OverflowError: overflow converting long int to machine word

MicroPython v1.11-8-g48dcbbe60 on 2019-05-29; ESP module with ESP8266
Type "help()" for more information.`

can you point me on how to avoid this

**Comment by costastf** [comment]
Hi @yukthr that would be line with
```
 esp.deepsleep(1000000 * duration)
```
. What I guess happens is that your board is low on memory and overflows on converting the long int. I guess you could play around with the size of int that your board can handle and adjust the code accordingly. Not sure how else to help here.

**Comment by yukthr** [comment]
Thank you for the swift response, will look into it. 

-Rakesh
